Repository litmuschaos/litmus-e2e, pull requests merged in 2020-07, with the labels that each got.

#152 chore(BDDs): Refactor Operator BDDs and shift it to a separate folder
  .gitlab-ci.yml
  Makefile
  operator/admin-mode_test.go
  operator/reconcile-resiliency_test.go
  pkg/utils/clienset.go
  pkg/utils/env.go
  pkg/utils/file.go
  pkg/utils/statusCheck.go
  tests/admin-mode_test.go
  tests/container-kill_test.go
  tests/disk-fill_test.go
  tests/install-litmus_test.go
  tests/kubelet-service-kill_test.go
  tests/node-cpu-hog_test.go
  tests/node-drain_test.go
  tests/node-memory-hog_test.go
  tests/pod-cpu-hog_test.go
  tests/pod-delete_test.go
  tests/pod-memory-hog_test.go
  tests/pod-network-corruption_test.go
  tests/pod-network-latency_test.go
  tests/pod-network-loss_test.go
  tests/reconcile-resiliency_test.go
  types/types.go
  vendor/github.com/onsi/gomega/go.mod
Labels: enhancement

#162 Added Cypress E2E folder and basic configurations
  .gitignore
  .gitlab-ci.yml
  CypressE2E/cypress.json
  CypressE2E/cypress/fixtures/example.json
  CypressE2E/cypress/integration/Login/login.spec.js
  CypressE2E/cypress/integration/Workflow/workflow.spec.js
  CypressE2E/cypress/plugins/index.js
  CypressE2E/cypress/support/commands.js
  CypressE2E/cypress/support/index.js
  CypressE2E/package-lock.json
  CypressE2E/package.json
Labels: enhancement

#163 update(README): Add Batch and update all the README.md files
  README.md
  generic-pipeline/README.md
  generic-pipeline/container-kill/README.md
  generic-pipeline/disk-fill/README.md
  generic-pipeline/kubelet-service-kill/README.md
  generic-pipeline/node-cpu-hog/README.md
  generic-pipeline/node-drain/README.md
  generic-pipeline/node-memory-hog/README.md
  generic-pipeline/pod-cpu-hog/README.md
  generic-pipeline/pod-delete/README.md
  generic-pipeline/pod-memory-hog/README.md
  generic-pipeline/pod-network-corruption/README.md
  generic-pipeline/pod-network-duplication/README.md
  generic-pipeline/pod-network-latency/README.md
  generic-pipeline/pod-network-loss/README.md
  openebs-pipeline/README.md
  openebs-pipeline/openebs-control-plane-chaos/README.md
  openebs-pipeline/openebs-pool-pod-failure/README.md
  openebs-pipeline/openebs-target-container-failure/README.md
  openebs-pipeline/openebs-target-network-delay/README.md
  openebs-pipeline/openebs-target-network-loss/README.md
  openebs-pipeline/openebs-target-pod-failure/README.md
Labels: documentation

#157 feat(e2e): Add Master plan yaml for getting the generic e2e pipeline test coverage
  .gitlab-ci.yml
  .master-plan.yml
  Makefile
  metrics/e2e-metrics
Labels: enhancement

#169 feat(litmuschaos-ci): Add customised GitHub page for LitmusChaos frontend representation
  README.md
  _config.yml
  _layouts/template.html
  generic-pipeline/generic.md
  images/litmus-footer.png
  images/litmus-logo.jpg
  index.md
  openebs-pipeline/README.md
  openebs-pipeline/openebs.md
  stylesheets/github-light.css
  stylesheets/normalize.css
  stylesheets/stylesheet.css
Labels: kind/enhancement, litmuschaos-ci

#168 feat(coverage): Add master plan yaml for getting the coverage percentage for openebs pipeline
  .gitlab-ci.yml
  .master-plan.yml
  Makefile
  metrics/e2e-metrics
Labels: kind/enhancement

#175 update(readme): Update readme to take a new table with coverage
  README.md
  generic-pipeline/generic.md
  openebs-pipeline/openebs.md
Labels: kind/enhancement

#174 feat(coverage): Add coverage percentage bar in readme and ci website for generic
  metrics/e2e-metrics
  pkg/utils/update.go
  tests/pipeline-update_test.go
  utils/pipeline_status_update.py
  vendor/github.com/onsi/gomega/go.mod
  vendor/modules.txt
Labels: kind/enhancement

#176 feat(coverage): Add coverage percentage in readme for openebs
  metrics/e2e-metrics
  pkg/utils/update.go
  tests/pipeline-status-update_test.go
  utils/pipeline_status_update.py
Labels: kind/enhancement
